- README.md
- examples/styles/styles.go
- examples/styles/styles.tape
- styles.go
- text.go
Add the ability to style certain keys
Fixes: https://github.com/charmbracelet/log/issues/14
Example:
```go
package main
import (
"fmt"
"github.com/charmbracelet/lipgloss"
"github.com/charmbracelet/log"
)
func main() {
log.KeyStyles["err"] = lipgloss.NewStyle().Foreground(lipgloss.Color("#ff0000"))
err := fmt.Errorf("too much sugar")
log.Error("failed to bake cookies", "err", err)
}
```
> feat(styles): style certain keys

- text.go
- text_test.go
Update to essentially render lipgloss styles for values after escaping and indenting.
- Add `l *looger` receiver to `writeEscapedForOutput` for access to `l.noStyles`
- Add `l *logger` receiver to `writeIdent` to be able to call the updated `writeEscapedForOutput`
- Update `writeEscapedForOutput` to call `ValueStyle.Render` after escaping the values, or if the values don't need need escaping
Fix #19
> fix(text) escape value before rendering styles

- text.go
- text_test.go
Fixes: https://github.com/charmbracelet/log/issues/19
> Fix styling value before rendering

- README.md
Tiny README update to including missing `Info` stuff from the levels section.
> docs: add missing info level info to README

- README.md
- logger.go
- logger_test.go
- pkg.go
- pkg_test.go
Adds `Debugf`, `Infof`,  `Warnf`, `Errorf`, `Fatalf`, and `Printf`. Use these in conjunction with `With(...)` to add more context to the log. `log.With("err", err).Errorf("user %s", user)`
Fixes: https://github.com/charmbracelet/log/issues/32
> feat(log): add format methods

- logger.go
- logger_test.go
- pkg.go
- pkg_test.go
Creates a sub-logger with the given prefix.
Fixes: https://github.com/charmbracelet/log/issues/36
> feat(log): sub-logger with prefix

- logger.go
- options.go
- options_test.go
- pkg.go
Format caller source file, line and function name.
Fixes: https://github.com/charmbracelet/log/issues/22
> feat(caller): add caller formatter

- go.mod
- logger.go
- pkg.go
Cache and reuse lipgloss renderers to avoid concurrently querying the terminal for background colors. Lipgloss HasDarkBackground function queries the terminal for the background color. Creating multiple logger instances with the same output will query the output multiple times causing Log to hange and/or freeze.
To solve this, we store and retrieve the Lipgloss renderer in a global sync.Map for each output along with caching the background/foreground colors of the underlying Termenv Output.
Fixes: https://github.com/charmbracelet/log/issues/50
> fix(output): cache lipgloss renderers

- logger.go
- logger_test.go
- added small unittest to highlight the problem
- problem only visible when running with `-race` option
> fix log.With() race condition

- logger.go
- logger_test.go
- stdlog.go
Before, `StandardLog` used to _copy_ the internal buffer causing two or
more loggers to share the same buffer triggering a race.
Don't copy the internal buffer and reduce the mutex critical section
scope.
Fixes: https://github.com/charmbracelet/log/issues/67
> fix: race condition when creating standard logger 

- logger.go
- pkg.go
- pkg_test.go
- text_test.go
Add `SetColorProfile` to force change the Lip Gloss renderer color profile.
Needs: https://github.com/charmbracelet/lipgloss/pull/212
Fixes: https://github.com/charmbracelet/log/pull/63
> feat: set lipgloss renderer color profile

- .gitignore
- logger.go
- logger_test.go
- text.go
resolves #78 
This PR handles empty messages, so that you can use 'just' structured logging while using the text formatter, by skipping the message block.
This pr also aligns all the cases to 'add a space when you need one for this loop' instead of some being that way and others being 'add a space because there will be a next loop'.
An impact to non-text logger, if you provide empty message through message parameter no message is sent. I think if you sent a 'msg' key with an empty string that would still end up in the file.
I gitignored .vscode .history and go.work, sometimes they are needed but they get accidentally committed randomly so it made sense to me to ignore them until there is an active file to be committed for those.
I added 3 new tests, and didn't make any new tests fail,,, …
> Handle Empty Messages

- logger.go
- pkg.go
- styles.go
- text.go
- text_test.go
Move styles to a per logger instance bases.
> feat: set custom styles

- level.go
- level_test.go
resolves #79 
this adds an error result to the parse level function.
this change changes the return signature for ParseLevel!
users of ParseLevel will need to handle the error or choose to disregard it.
people will see the 'multiple values in a single context' error like below
```
log on  strict-parse-level [!?] via 🐹 v1.21.3 
  ❯ go test 
.\level_test.go:58:33: multiple-value ParseLevel(tc.level) (value of type (Level, error)) in single-value context
FAIL    github.com/charmbracelet/log [build failed]
```
> Return Error from ParseLevel

- styles.go
Don't use AdaptiveColors and use regular colors instead. This makes the default styles _not_ use HasDarkBackground to determine the terminal background color. HasDarkBackground will query the terminal for the background color using `OSC 11` to determine which color to use in AdaptiveColor.
For users who still want to use AdaptiveColors, they can supply their own custom styles.
Fixes: https://github.com/charmbracelet/log/issues/90
> fix: use const colors to skip reading querying for the terminal bg color

- logger.go
- logger_test.go
- pkg.go
- pkg_test.go
- text.go
- text_test.go
Exposing `logger.Log` makes it possible to use a custom log level to log messages. Simply define a new level and use `Log` and `Logf` to log messages using the newly defined level.
Fixes: https://github.com/charmbracelet/log/issues/89
> feat: expose log function

- options.go
The default is `ShortCallerFormatter`
> Options.CallerFormatter documentation issue

- README.md
Replaced `function` with `func` in the sample code snippet within the README.
I made this change because I thought it was a typo, since `function` is not recognized by Go. However, if you have a particular reason for using `function` in this context, you may ignore this PR.
> docs: Replace `function` with `func` in README sample code

- examples/README.md
In an attempt to improve our documentation while keeping the cost of maintenance as low as possible, I think it would be valuable to direct users on how to use the examples provided. A lot of people who are new to Go aren't aware that they can see the godoc of our packages online. 
Lmk your thoughts, I *think* this disclosure makes it easier for users to learn to find what they're looking for.
> docs: direct users to library API

- context.go
- pkg.go
The default logger will try to query background et al on startup, which might conflict with other libs trying to query it too.
It's easily reproducible with some of our tools that use the log package, e.g., VHS:
```sh
faketty vhs --help
```
It slows down the program quite a bit, and print some ansi escape sequences as well.
This patch changes it so it only inits the default logger when/if the default logger is used.
Per my testing, it seems to fix the original issue.
> fix: lazy init default logger

- pkg.go
- pkg_test.go
This adds synchronisation primitives around all uses of the `defaultLogger`.
`atomic.Pointer` was introduced in Go 1.19. I see you have 1.19 in `.github/` and `go.mod`, but maybe you still try to be backwards compatible? If so, I can replace `atomic.Pointer` with `atomic.Value`.
**UPDATE**: I see now that in #111, on purpose we delay initialisation of the logger. Reading about [init in Effective Go] it looks like using `func init()` should work fine.
> [..] init is called after all the variable declarations in the package have evaluated their initializers, and those are evaluated only after all the imported packages have been initialized. 
(An alternative solution exists at e31f99cb but is more complicated imho. Most likely the problem with escape sequence during initialisation was …
> fix: data race in Default and SetDefault

- logger.go
- logger_test.go
sl.fields and l.fields reference the the same object, when we create multiple goroutines and bump loggers with the With() method, the golang race detector will complain about this.
> fix: deep copy the fields to avoid data race

- json.go
- logger_121.go
- logger_121_test.go
- logger_no121.go
This adds support for slog attributes and fixes #119.
> feat: support slog attributes

- examples/README.md
Fixed Broken link in examples/README.md
> docs: Fixing broken links in the examples/README.md

- level.go
- logger.go
- logger_121.go
- logger_no121.go
- pkg.go
_Marking this as draft to gather feedback_
The `Level` type (`int32`) is currently slightly incompatible with stdlib's `slog.Level` type, which is an `int`. This means it's impossible to safely cast a `slog.Level` to a `charmlog.Level`, without risking an overflow. (Practically speaking, that's very unlikely, but try telling that to the linter 😆).
This PR changes `type Level int32` to `type Level int` and updates some places where `atomic.StoreInt32` was called to `atomic.StoreInt64`.
It's entirely possible that this change isn't safe, and that there's already enough code out there that expects `charmlog.Level` to be an `int32` that this would break enough folks not to be worth it.
But, if this change is doable, it would make it slightly easier for code that uses this package to …
> change type of Level to int

- json.go
- json_test.go
- logger_121.go
- logger_no121.go
We need to type check any value to see if it is an error. While doing so, we also need to check if it doesn't have a json.Marshaler interface to avoid overwriting the error message with the marshaled value.
Fixes: https://github.com/charmbracelet/log/issues/170
> fix: ensure we recognize errors as slog.AnyValue

- json.go
- json_test.go
- logfmt.go
- logfmt_test.go
- logger.go
- logger_121.go
- logger_121_test.go
- logger_no121.go
- logger_test.go
- options.go
- options_test.go
- pkg.go
- pkg_test.go
- text.go
- text_test.go
This pr is a simple update.  Changes `interface{}` type references to `any`.   I noticed the language server gives a warning about `interface{} can be replaced by any`.  The `any` keyword was introduced in go 1.18 and this project uses 1.19 and above.  using `any` is the idiomatic way in modern go so I figured Id make the change.
> change interface{} to any
